name: Iterate over directories
on:
  push:
    branches:
      - main

jobs:
  iterate-directories:
    runs-on: ubuntu-latest
    steps:
      - name: Find all directories
        run: |
          find . -type d

      - name: Iterate over directories
        for_each: directory in $(find . -type d) do
          run: |
            echo "Processing directory: $directory"
            if [ -f "$directory/Dockerfile" ]; then
              echo "Removing Dockerfile from $directory"
              echo "rm $directory/Dockerfile"
              rm $directory/Dockerfile
            fi
        end
# env:
#   REGISTRY: ghcr.io
#   IMAGE_NAME: ${{ github.repository }}

# jobs:
#   generateInputPaths:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: Generate matrix with all modules of WhatTheHack repository
#         id: set-matrix
#         run: |
#           echo "::set-output name=matrix::$(ls -l | grep '^d' | awk -F ' ' '{print $9}' | jq -R -s -c 'split("\n") | map(select(length > 0))')"
#     outputs:
#       matrix: ${{ steps.set-matrix.outputs.matrix }}
#   build:
#     needs: generateInputPaths
#     runs-on: ubuntu-latest
#     strategy:
#       fail-fast: false
#       matrix:
#         path: ${{ fromJson(needs.generateInputPaths.outputs.matrix) }}
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3
#       - name: changing directory
#         run: |
#           ENV
#       - name: Log in to the Container registry
#         uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
#         with:
#           registry: ${{ env.REGISTRY }}
#           username: ${{ github.actor }}
#           password: ${{ secrets.GITHUB_TOKEN }}
#       - name: Extract metadata (tags, labels) for Docker
#         id: meta
#         uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
#         with:
#           images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
#       - name: Build and push Docker image
#         uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
#         with:
#           context: .
#           push: true
#           tags: ${{ steps.meta.outputs.tags }}
#           labels: ${{ steps.meta.outputs.labels }}
