name: Build nginx

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * *'
  push:
    branches:
      - "**"
    paths:
      - "nginx"
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/fmotalleb/php-supervisor

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag: [
          "fpm-bookworm", 
          "8.3-rc-fpm-bookworm",
          "8.2-fpm-bookworm", 
          "8.1-fpm-bookworm",
        ]
        # path: 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          context: .
          file: ./nginx/Dockerfile
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          context: .
          file: ./nginx/Dockerfile
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          file: ./nginx/Dockerfile
          build-args: PHP_VERSION=${{ matrix.tag }}
          push: true
          tags: ${{ env.IMAGE_NAME }}:nginx-${{ matrix.tag }}
          labels: ${{ steps.meta.outputs.labels }}
